# Generated by Django 6.0.7 on 2026-07-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_category_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auto_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
