# Generated by Django 6.0.7 on 2026-07-31 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_categories_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='auto_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
