# Generated by Django 6.0.7 on 2026-08-23 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_categories_auto_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
