# Generated by Django 6.0.7 on 2026-08-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_categories_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
