# Generated by Django 6.0.7 on 2026-08-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_commission_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_delivery_days',
            field=models.PositiveIntegerField(default=7, help_text='Maximum days for delivery (e.g. 7)'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_delivery_days',
            field=models.PositiveIntegerField(default=3, help_text='Minimum days for delivery (e.g. 3)'),
        ),
    ]