# Generated by Django 6.0.7 on 2026-08-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_commission_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Agent commission % earned on this product', max_digits=5),
        ),
    ]