# Generated by Django 6.0.7 on 2026-09-03 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_mrp_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant_label',
            field=models.CharField(blank=True, help_text="Is specific product ka variant value — jaise: '10 Watt', '15L', 'Cocoa Brown'", max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_of',
            field=models.ForeignKey(blank=True, help_text="Agar ye kisi product ka variant (color/size/wattage/capacity) hai, us 'main' product ko yahan select karo", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='products.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_type',
            field=models.CharField(blank=True, help_text='Variant ka naam — jaise: Wattage, Capacity, Colour, Size (sabhi variants mein same rakhna)', max_length=30),
        ),
    ]
